# Generated by Django 2.1.5 on 2019-01-21 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dbItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quickname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('item_url', models.URLField(max_length=2083)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('children', models.ManyToManyField(to='indiek_web.dbItem')),
            ],
        ),
        migrations.CreateModel(
            name='dbTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subtopics', models.ManyToManyField(to='indiek_web.dbTopic')),
            ],
        ),
        migrations.AddField(
            model_name='dbitem',
            name='topics',
            field=models.ManyToManyField(to='indiek_web.dbTopic'),
        ),
    ]
