# Generated by Django 2.1.5 on 2019-01-27 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indiek_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbitem',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, to='indiek_web.dbItem'),
        ),
        migrations.AlterField(
            model_name='dbitem',
            name='topics',
            field=models.ManyToManyField(blank=True, limit_choices_to={'author': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)}, null=True, to='indiek_web.dbTopic'),
        ),
    ]
