# Generated by Django 2.1.5 on 2019-02-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiek_web', '0003_auto_20190127_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbitem',
            name='topics',
            field=models.ManyToManyField(blank=True, to='indiek_web.dbTopic'),
        ),
    ]
